name: Skyramp Python UI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  python-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install skyramp pytest-playwright pytest
          python -m playwright install --with-deps chromium

      - name: Generate UI test from trace
        run: |
          skyramp generate ui rest \
          --language python \
          --framework pytest \
          --playwright-trace tests/demo.zip

      - name: Run Python test
        run: |
          python3 -m pytest tests/ui-demo-python.py --browser chromium
