name: Python Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    # Cache pip dependencies
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    # Cache Playwright browsers
    - name: Cache Playwright browsers
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-browsers
        restore-keys: |
          ${{ runner.os }}-playwright-browsers
    
    - name: Install dependencies and Skyramp deps
      run: |
        python -m pip install --upgrade pip
        pip3 install skyramp pytest-playwright pytest
    
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps
    
    - name: Run your tests
      run: |
        for file in skyramp_tests/*.py; do
          if [ -f "$file" ]; then
            echo "Running tests in $file"
            python3 -m pytest "$file" -v
          fi
        done