name: Skyramp Python UI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  python-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install skyramp pytest-playwright pytest
          python -m playwright install --with-deps chromium

      - name: Generate & run for each trace
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          zips=(tests/*.zip)

          if (( ${#zips[@]} )); then
            echo "Found ${#zips[@]} trace zip(s): ${zips[*]}"
            for z in "${zips[@]}"; do
              echo "::group::Generate from $z"
              skyramp generate ui rest \
                --language python \
                --framework pytest \
                --playwright-trace "$z"
              echo "::endgroup::"

              echo "::group::Run pytest for $z"
              python3 -m pytest tests/ui-demo-python.py --browser chromium -q
              echo "::endgroup::"
            done
          else
            echo "No zip traces found — skipping run."
          fi
