name: Skyramp TypeScript UI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ts-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies (user)
        run: |
          npm install @skyramp/skyramp @playwright/test
          npx playwright install --with-deps chromium
          pip3 install --user skyramp

      - name: Add local bin to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Generate & run per zip
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          zips=(tests/*.zip)

          if (( ${#zips[@]} == 0 )); then
            echo "No zip traces found — skipping run."
            exit 0
          fi

          for z in "${zips[@]}"; do
            echo "::group::Generate from $z"
            marker="$(date +%s)"
            skyramp generate ui rest \
              --language typescript \
              --framework playwright \
              --playwright-trace "$z"
            echo "::endgroup::"

            echo "::group::Run newly generated tests for $z"
            mapfile -t new_specs < <(find . -type f -name "*.spec.ts" -newermt "@$marker")
            if (( ${#new_specs[@]} )); then
              printf 'Detected new TS specs:\n%s\n' "${new_specs[@]}"
              npx playwright test "${new_specs[@]}" --reporter=list
            else
              echo "No new TypeScript spec files detected for $z"
            fi
            echo "::endgroup::"
          done
