name: Skyramp TypeScript UI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ts-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm install @skyramp/skyramp @playwright/test
          npx playwright install --with-deps chromium

      - name: Generate UI test from trace
        run: |
          skyramp generate ui rest \
          --language typescript \
          --framework playwright \
          --playwright-trace tests/demo.zip

      - name: Run TS test
        run: |
          npx playwright test tests/ui-demo-typescript.spec.ts --reporter=list
